
greeting: Hello Local

#eureka:
 # client:
  #  registryFetchIntervalSeconds: 5

#fortunes:
 # ribbon:
  #  ServerListRefreshInterval: 5000

security:
  basic:
    enabled: false

endpoints:
  health:
    sensitive: false
---


