server:
   port: 8081



spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
    services:
      registrationMethod: route 

security:
  basic:
    enabled: false
---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
  jpa:
#    database: POSTGRESQL
     database: HSQL

---

spring:
  profiles: c2c
  cloud:
    services:
      registrationMethod: direct
