---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet 

inputs:
- name: cloud-native-tour-repo
outputs:
- name: build 

run:
  path: cloud-native-tour-repo/fortune-teller-dotnet/src/AspDotNetCore/Fortune-Teller-UI/ci/build.sh 
