---
resources:
- name: at-night
  type: time
  source:
    start: 4:00 AM +0200
    stop: 5:00 AM +0200

- name: cloud-native-tour-repo
  type: git
  source:
    uri: https://github.com/ebornier-pivotal/cnt-fortune-teller.git 

- name: cf
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true

jobs:

- name: fortune-teller-fortune-service
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: cloud-native-tour-repo
    #trigger: true
    #passed: [ unit-test ]
  - task: build
    file: cloud-native-tour-repo/fortune-teller-fortune-service/ci/build.yml
  - put: cf
    params:
      manifest: cloud-native-tour-repo/fortune-teller-fortune-service/manifest.yml
      path: build/fortune-teller-fortune-service-0.0.1-SNAPSHOT.jar

- name: fortune-teller-ui
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: cloud-native-tour-repo
    #trigger: true
    #passed: [ unit-test ]
  - task: build
    file: cloud-native-tour-repo/fortune-teller-ui/ci/build.yml
  - put: cf
    params:
      manifest: cloud-native-tour-repo/fortune-teller-ui/manifest.yml
      path: build/fortune-teller-ui-0.0.1-SNAPSHOT.jar
