
server:
   port: 8082

info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    FORTUNE: /service/**
    UI: /**
    zuulserver: /self/**

security:
  basic:
    enabled: true 
  user: 
    name: admin
    password: password
logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
